version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: qiwi_postgres_local
    environment:
      POSTGRES_USER: bePay_user
      POSTGRES_PASSWORD: G7x!r9Qv2@secure
      POSTGRES_DB: qiwi_gateway
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bePay_user -d qiwi_gateway"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
